#Univariate Feature

In [2]:
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


In [7]:
filename = '/content/pima-indians-diabetes.data.csv'
# In actual Datasets columns names are not given so giving the columns name
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
diabetes = read_csv(filename,names=names)
array = diabetes.values
diabetes.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [5]:
diabetes.shape

(771, 9)

In [6]:
diabetes.isna().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [9]:
#Divide the data into diabetes1 and diabetes2
diabetes1=array[:,0:8]
diabetes2=array[:,8]

In [ ]:
diabetes1

In [ ]:
diabetes2

In [12]:
#Feature Extraction
test = SelectKBest(score_func=chi2,k=5) # To get Top 5 Best Feature
fit=test.fit(diabetes1,diabetes2)

In [16]:
set_printoptions(precision=4) #Precision is after decimal  how many  digits you want to chi-square value
print(fit.scores_)

[ 113.5 1424.2   17.1   51.5 2178.7  129.7    5.4  183.1]


In [17]:
names  # max chi square value is for test so test is best feature

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [32]:
diabetes3 = pd.DataFrame(fit.scores_).T  # Paas the chi square value in to Data Frame

In [33]:
diabetes3

0           1         2          3            4           5  \
0  113.539739  1424.20666  17.06232  51.462865  2178.688159  129.651773   

          6           7  
0  5.395356  183.113153

In [34]:
diabetes3.columns=names[:8]  #as per chi square test , test is most imp feature,Next: plas

In [35]:
diabetes3

preg        plas      pres       skin         test        mass  \
0  113.539739  1424.20666  17.06232  51.462865  2178.688159  129.651773   

       pedi         age  
0  5.395356  183.113153

In [38]:
diabetes3.max(1) #test is most imp feature

0    2178.688159
dtype: float64

In [43]:
#Sort the chi square values in Ascending Order
sortes_diabetes3 = diabetes3.sort_values(by=0,ascending=False,axis=1)

In [44]:
sortes_diabetes3

test        plas         age        mass        preg       skin  \
0  2178.688159  1424.20666  183.113153  129.651773  113.539739  51.462865   

       pres      pedi  
0  17.06232  5.395356

In [45]:
diabetes

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0
768     1    95    75    35     0  30.5  0.319   25      0
769     9   170    74    31     0  44.0  0.403   43      1
770     7   137    90    41     0  32.0  0.391   39      0

[771 rows x 9 columns]

#Recursive Feature Elimination


In [46]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
filename = '/content/pima-indians-diabetes.data.csv'
# In actual Datasets columns names are not given so giving the columns name
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
diabetes = read_csv(filename,names=names)
array = diabetes.values
diabetes1=array[:,0:8]
diabetes2=array[:,8]

In [48]:
#Feature Extraction
model = LogisticRegression(max_iter=400)  #Default iteration value is 100
rfe = RFE(model)
fit=rfe.fit(diabetes1,diabetes2)

In [49]:
fit.n_features_ #4 Top Features Are Available

4

In [50]:
#Selected Features
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [51]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [52]:
fit.ranking_  #Feature Ranking by Ranking like 1 =most imp 2= second imp

array([1, 1, 3, 5, 4, 1, 1, 2])

#Feature Importance using Decision Tree

In [57]:
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier
filename = '/content/pima-indians-diabetes.data.csv'
# In actual Datasets columns names are not given so giving the columns name
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
diabetes = read_csv(filename,names=names)
array = diabetes.values
diabetes1=array[:,0:8]
diabetes2=array[:,8]
#Feature Extraction
model = DecisionTreeClassifier()
model.fit(diabetes1,diabetes2)
print(model.feature_importances_)

[0.1 0.3 0.1 0.  0.  0.2 0.1 0.1]


In [59]:
sorted_list=model.feature_importances_
print('feature_importances=',sorted_list)
sorted_list.sort()
print('Sorted Feature importance=',sorted_list)


feature_importances= [0.1 0.3 0.1 0.  0.  0.2 0.1 0.1]
Sorted Feature importance= [0.  0.  0.1 0.1 0.1 0.1 0.2 0.3]


In [60]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [64]:
# So highet value is for #Plas, followed by #mass, then #age, then #pedi and


In [ ]:
# select the best values from the all the features